import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
  },
  textStyle: {
    fontSize: 20,
    margin: 20,
    textAlign: 'center',
    justifyContent: 'center',
  },
  header: {
    marginTop: 30,
    marginBottom: 15,
    backgroundColor: '#f5baba',
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: "#f88a8a",
    borderRadius: 10,
  },
  footer: {
    marginTop: 20,
    backgroundColor: '#f5baba',
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: "#f88a8a",
    borderRadius: 10,
  },
  title: {
    color: '#fff',
    fontWeight: 'bold',
    flex: 1,
    fontSize: 23,
    textAlign: 'center',
    margin: 10,
  },
  author: {
    color: '#fff',
    fontWeight: 'bold',
    flex: 1,
    fontSize: 15,
    textAlign: 'center',
    margin: 10,
  },
  gameboard: {
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center'
  },
  infoTitle: {
    fontSize: 20,
    color: "#f88a8a",
    margin: 10,
    fontWeight: 'bold',
  },
  gameinfo: {
    backgroundColor: '#fff',
    textAlign: 'center',
    justifyContent: 'center',
    fontSize: 16,
    margin: 10,
  },
  row: {
    marginTop: 10,
    padding: 10,
  },
  flex: {
    flexDirection: "row"
  },
  textInput: {
    borderStyle: 'solid',
    borderWidth: 2,
    borderColor: '#f5baba',
    borderRadius: 10,
    padding: 5,
    width: 200,
  },
  button: {
    margin: 10,
    flexDirection: "row",
    padding: 10,
    backgroundColor: "#f88a8a",
    width: 100,
    borderRadius: 20,
    justifyContent: 'center',
    alignSelf: 'center',
  },
  clearButton: {
    margin: 10,
    flexDirection: "row",
    padding: 10,
    backgroundColor: "#f88a8a",
    width: 200,
    borderRadius: 20,
    justifyContent: 'center',
    alignSelf: 'center',
  },
  buttonText: {
    color:"#ffffff",
    fontSize: 16,
  },
  playerName: {
    fontSize: 24,
    padding: 10,
    color: '#f88a8a',
    textAlign: 'center',
    justifyContent: 'center',
    fontWeight: 'bold',
  },
  totalPoints: {
    fontSize: 26,
    padding: 10,
    color: '#f88a8a',
    textAlign: 'center',
    justifyContent: 'center',
    fontWeight: 'bold',
  },
  savePoints: {
    fontSize: 20,
    backgroundColor: "#f88a8a",
    padding: 5,
    borderRadius: 5,
  },
  newGame: {
    fontSize: 20,
    backgroundColor: "#f88a8a",
    padding: 10,
    borderRadius: 5,
    fontWeight: 'bold',
  },
  gameEndStatus: {
    fontSize: 24,
    marginTop: 10,
    color: '#a56262',
    textAlign: 'center',
    justifyContent: 'center',
    fontWeight: 'bold',
  },
  dataTable: {
    flex: 1,
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#f88a8a',
  },
});